{% set name = "pyxirr" %}
{% set version = "0.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyxirr-{{ version }}.tar.gz
  sha256: 550ca1660d92e49da56a171bac22d152c5cf44abc9a031197f5b537f6dba368e

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyxirr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Anexen/pyxirr
  summary: Rust-powered collection of financial functions for Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
