{% set name = "pyxirr" %}
{% set version = "0.10.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Anexen/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: 3470ff6cecd4b100770e220a94b63d9769748c228ca7f3d0fbd44d0b1c8699e6

build:
  number: 0
  skip: true  # [py<37] or [py>313]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - maturin >=1,<2
    - pip
    - python
  run:
    - python


test:
  imports:
    - pyxirr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Anexen/pyxirr
  summary: Rust-powered collection of financial functions for Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
