{% set name = "pyxirr" %}
{% set version = "0.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Anexen/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: 384b06a9671398e692d3b146fe1cd5e9db4105b7c174bd3790cd0d73758abbe4

build:
  number: 0
  skip: true  # [py<37] or [py>312]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - maturin >=1,<2
    - pip
    - python
  run:
    - python


test:
  imports:
    - pyxirr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Anexen/pyxirr
  summary: Rust-powered collection of financial functions for Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
