{% set name = "pyxirr" %}
{% set version = "0.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Anexen/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: e1c9ce7cd0e8340f96cf0d66f0733d83e3eb32098e5227d5a0d421470ac99f00

build:
  number: 0
  skip: true  # [py<37] or [py>312]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=1,<2
    - pip
    - python
  run:
    - python

    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - pyxirr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Anexen/pyxirr
  summary: Rust-powered collection of financial functions for Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
