{% set name = "pyxirr" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Anexen/{{ name }}/archive/refs/tags/v{{ version }}.zip
  sha256: 856c5409bd001554d55de938dfa77a7506dc0cf9d1e9e3466aa566d4522c0991

build:
  number: 0
  skip: true  # [py<37] or [py>312]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - maturin >=1,<2
    - pip
    - python
  run:
    - python

test:
  imports:
    - pyxirr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Anexen/pyxirr
  summary: Rust-powered collection of financial functions for Python.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
